global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "cricket"
    scrape_interval: 10s
    static_configs:
      - targets: ["192.168.1.78:80"] # /metrics

rule_files:
  - alert_rules.yml
