global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "cricket"
    scrape_interval: 10s
    static_configs:
      - targets: ["nginx:1337"] # /metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - alert_rules.yml
